baseurl = "/"
languageCode = "en-us"
title = "Steffens test"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Test"
    url = "https://github.com/rstudio/blogdown"
    weight = 1
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"
    weight = 3
    
[[menu.main]]
    name = "Posts"
    pre = "fa-bullhorn"
    url = "/post/"
    weight = 4

[params]
    description = "Super website :heart:"
    

    customCSS = ["css/erum.css"]
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "eRum2020.png"
    width = 50
    height = 50
    alt = "Logo"

